### ISSUE TITLE
report error:'analyzeHeadless' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by KyleLeith-007** [galoget/ghidra-headless-scripts#1]
report error:'analyzeHeadless' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

**Comment by galoget** [comment]
In Ghidra, the `analyzeHeadless` binary is typically located within the installation directory of Ghidra. However, the exact location can vary depending on your operating system and how Ghidra was installed.

It's often found in the `Ghidra\support\` directory within the Ghidra installation folder. Please, see the screenshot below as a reference.

![image](https://github.com/galoget/ghidra-headless-scripts/assets/8353133/9236c33c-018b-4388-baa7-2b5d76da8e66)

If you're having trouble locating it, you can try searching within the Ghidra installation directory for "analyzeHeadless".

**Comment by KyleLeith-007** [comment]
> In Ghidra, the `analyzeHeadless` binary is typically located within the installation directory of Ghidra. However, the exact location can vary depending on your operating system and how Ghidra was installed.
> 
> It's often found in the `Ghidra\support\` directory within the Ghidra installation folder. Please, see the screenshot below as a reference.
> 
> ![image](https://private-user-images.githubusercontent.com/8353133/333866263-9236c33c-018b-4388-baa7-2b5d76da8e66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MTQ5OTcsIm5iZiI6MTcxNjcxNDY5NywicGF0aCI6Ii84MzUzMTMzLzMzMzg2NjI2My05MjM2YzMzYy0wMThiLTQzODgtYmFhNy0yYjVkNzZkYThlNjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjZUMDkxMTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGIwOWIzNTVjYTE5YzcyYzQyNWYwMTFmYjU2MzY5YTNjMjg0ZGE0MjJlNWY0MjBlOTY2MWEyMDFlZWVhMTJjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ycG2Muu6QXkY7DMLCmv0n1nv5zAndyIgZuxq-gMxGus)
> 
> If you're having trouble locating it, you can try searching within the Ghidra installation directory for "analyzeHeadless".

Thank you very much for your reply. I followed your instructions and it was successful!

**Comment by galoget** [comment]
You're welcome, glad to hear that!  =)
